run:
  timeout: 10m

issues:
  max-same-issues: 100

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errorlint
    - exportloopref
    - forcetypeassert
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
